// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC06zI7IiF-Sf5bgTKaOL1KS713ZEZ065w',
    appId: '1:582331983288:web:1860d148a5ff8d17c69b4d',
    messagingSenderId: '582331983288',
    projectId: 'child-rights-0010',
    authDomain: 'child-rights-0010.firebaseapp.com',
    storageBucket: 'child-rights-0010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5alMfJvDwo8AilZ9_qPAGbvgeC7bPcLA',
    appId: '1:582331983288:android:d70780bd8df7cf83c69b4d',
    messagingSenderId: '582331983288',
    projectId: 'child-rights-0010',
    storageBucket: 'child-rights-0010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEkyK4EvEKh6L3Zv1xZ07X3PYpTXaFkMY',
    appId: '1:582331983288:ios:aa815e328e6cb6edc69b4d',
    messagingSenderId: '582331983288',
    projectId: 'child-rights-0010',
    storageBucket: 'child-rights-0010.firebasestorage.app',
    iosBundleId: 'com.example.hicodechildrights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEkyK4EvEKh6L3Zv1xZ07X3PYpTXaFkMY',
    appId: '1:582331983288:ios:aa815e328e6cb6edc69b4d',
    messagingSenderId: '582331983288',
    projectId: 'child-rights-0010',
    storageBucket: 'child-rights-0010.firebasestorage.app',
    iosBundleId: 'com.example.hicodechildrights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC06zI7IiF-Sf5bgTKaOL1KS713ZEZ065w',
    appId: '1:582331983288:web:f9fd745da9cb7366c69b4d',
    messagingSenderId: '582331983288',
    projectId: 'child-rights-0010',
    authDomain: 'child-rights-0010.firebaseapp.com',
    storageBucket: 'child-rights-0010.firebasestorage.app',
  );
}
